### ISSUE TITLE
PROCEDURE autocomplete error

### ISSUE THREAD

**Issue by shiplett** [phileagleson/poweron-vscode#1]
Receiving the following error when writing a procedure, and trying to close it.

Specifically, if I type:
  PROCEDURE PRONAME

  END <---- error happens when I type END

Error text is:

[Error - 3:54:19 PM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read properties of undefined (reading 'toLowerCase')
  Code: -32603

**Comment by phileagleson** [comment]
@shiplett I just published a new version of the extension 0.6.7 that should fix the bug. Please let me know if you still have that issue.

**Comment by shiplett** [comment]
@phileagleson - that did resolve the issue, thanks!

I'm super pumped about this extension - i had started to create my own, and try to crib functionality from the RepDev project, but I think you are way ahead of me.

Another note - I had noticed that the extension does the end-tag completion for the IF/FOR etc. . . . and I thought it was particularly neat that the autocomplete for PROCEDURE appended the name.   That does not appear to be working right now though.

**Comment by phileagleson** [comment]
@shiplett I'm glad you're liking in so far. I don't actually use VS Code but I created the poweron-language-server and treesitter-poweron to use in neovim. That made it pretty easy to create a VS Code extension. The procedure name completion still seems to be working for me. When typing the word "PROCEDURE" are you selecting the completion item snippet? It should let you type the name and press "Tab" to move your cursor to inside the procedure while updating the end comment.  

PR's are also welcome if you have any ideas for functionality or bug fixes. That being said, pretty much all the functionality is provided by the language server

These things can change depending on your VS Code keybindings but this is a little more info on the functionality:
1.	Autocomplete for many things – like Database field names and poweron functions 
2.	Go to Definition – (Default Mapping: F12) works for variables and procedures and they can be in a different file as long as the file is in your workspace
3.	Find References – (Default Mapping: Shift + F12) works for variables and procedures and will show you everywhere in your workspace so across files, that variable or procedure is referenced.
4.	Rename Symbol – (Default Mapping: F2 – After hitting F2, SHIFT+ENTER will give you a rename preview, pretty cool) works for variables and procedures and will give you the option for only current file or across workspace (if not found in current define division)
5.	View All Symbols – (Default Mapping: CTRL+SHIFT+O) Shows all variables and Procedures defined in the current specfile. Helpful if you forgot what you called that procedure or variable.
6.	Smart Fold Ranges – No mapping, added automatically but helpful when you have some nested IF statements and need to know where one ends 
7.	Lots of Hover Info – If you Hover over a variable in the current file, you’ll see its declaration statement, All poweron functions will show the full eDocs documentation. All fields in the Account File will show the eDocs info for that field 
8.	A few Snippets – Kind of falls in with autocomplete but if you start typing an IF statement, or creating a division, you’ll get a snippet to autocomplete, you can “Tab” through placeholders in the snippet.
9.	Code Actions – Only 2 right now if you click the “light bulb” you can activate them – 1. Wrap selection in HTMLVIEWLINE – stole from rep dev. 2. If a variable is not defined in the current specfile, you’ll get an “Add to Define Division” Code Action.

I use "Go to definition" and "Find References" all day for troubleshooting.

**Comment by shiplett** [comment]
@phileagleson I'm not familiar with neovim - is that what you use for PowerOn editing?

I'll check out the auto-complete and see if I'm using it incorrectly.   And yes, I will take a look.  It seems pretty complete though.  I have a couple of things that I use, but they may be personal preferences.
